TOKEN_GITHUB = "567ea844af4b40d6cc346d663127ececfce05768"

STR_PLATFORM_NAME_GITHUB = "GitHub"
STR_PLATFORM_URL_GITHUB = "https://github.com/"

STR_EVENT_TYPE_PUSH = "PushEvent"
STR_EVENT_TYPE_COMMIT_COMMENT = "CommitCommentEvent"
STR_EVENT_TYPE_ISSUE_COMMENT = "IssueCommentEvent"
